transmission.cc
double phyRate[12][7][12][7]
List of physical rate with special Resource Units.
Referenced by destination::destination, getMacTransmissionTime, getTransmissionTimePayload.
double accessTimeAndAck
Only 20Hz, maximum tones of resource unit = 242, max number of clients = 9 4 resource unit avaiable: 26, 52, 106, 242.
int bandwidth
int maxTones
Referenced by ruAllocation, ruAllocationOptimal.
int maxClient
Referenced by fifoOFDMAOptimal.
int RuType[4][4]
Referenced by fifoOFDMAOptimal, getTransmissionTimeOfdmaFrame, ruAllocation, ruAllocationOptimal, ruBruteForce.
double getMacTransmissionTime(packet aPacket, int nbOfBytesMac, int ru)
Get the Mac Transmission Time of a packet (Layer 2: Data link layer)
aPacket nbOfBytesMac ru double
References packet::m_destination, destination::m_mcs, packet::m_size, phyRate.
Referenced by getTransmissionTimeOfdmaFrame.
int newDest(destination aDest, std::list< destination > destList)
Checking if it is a new destination founded or not.
aDest destList int (its index if old dest, -1 if new dest)
References destination::m_no.
Referenced by fifoOFDMAOptimal.
double alpha_i(packet pkt)
Time for transmit a packet.
pkt double
References packet::m_destination, destination::m_phyRate, packet::m_size.
Referenced by ruAllocation.
double getTransmissionTimeOfdmaFrame(std::list< packet > packetsList, std::vector< int > ruList)
Get the Transmission Time Ofdma Frame object.
packetsList List of packets ruList List of Resource Unit that correspond to each packet <double> Return the max transmition time packet's (cause all packet paralel)
References getMacTransmissionTime, RuType.
Referenced by fifoOFDMAOptimal, objectiveFunction.
int * ruAllocation(std::list< packet > pkt_set)
References alpha_i, maxTones, RuType.
void ruBruteForce(std::vector< int > ru, int noSta, std::list< std::vector< int > > &ruList)
Algorithm for generate all possile combination RU list for packet list.
ru blank vector at beginning noSta number of packet - 1 ruList list of vector of value of Ru index (A reference to a list where all possible combinations of RU allocations will be stored.)
References ruBruteForce, RuType.
Referenced by ruAllocationOptimal, ruBruteForce.
std::vector< int > ruAllocationOptimal(std::list< packet > packetsList)
Return a vector combines of RuTypes that optimal for packetList.
packetsList given list of packets std::vector<int>
References maxTones, objectiveFunction, ruBruteForce, RuType.
Referenced by fifoOFDMAOptimal.
double objectiveFunction(std::list< packet > packetsList, std::vector< int > ruList)
Calculate objective Function for given packet List and corresponding tones.
packetsList List of packets ruList List of Resource Unit correspond to packet list <double> Return the Objective Physical Rate for a packet list
References getTransmissionTimeOfdmaFrame.
Referenced by fifoOFDMAOptimal, ruAllocationOptimal.
double getTransmissionTimePayload(packet aPacket, int ru)
Get the Transmission Time Payload without byteMac (another layer) for a packet.
aPacket given packet ru resource unit <double>
References packet::m_destination, destination::m_mcs, packet::m_size, phyRate.
double fifo(list< packet > &buffer, double currentTime)
Calculate transmission time for FIFO.
buffer currentTime double
References buffer, currentTime, packet::m_arrival, packet::m_destination, destination::m_no, destination::m_phyRate, packet::m_size.
Referenced by transmitNextPackets.
double fifoAggregation(std::list< packet > &buffer, double currentTime)
Calculate transmission time for FIFO Aggregation, FIFO represents the process that you take the first packet in the packet list, check if any packets that have the same destination with the selected packet, aggregate all of thems into a frame called "Jumbo frame", then sending this jumbo to the corresponding destination, simultaneously erase the packet in the initial buffer. Do this till the buffer empty and calculate the total time for transmit them. CAREFUL: if aggregation happens then no need to increase iterator since after erase() the iterator automatically point to the next item.
buffer List of packets currentTime txOP Transmission Opportunity: Max time for a transmission occurs aggregation_frame_size Default max size for an aggregated frame frame_header_size Size of aggregated frame header no_aggregated_pkt Counter for aggregated packet aggregation Flag represents aggregation (yes or no) <double> Transmission time
References buffer, packet::m_destination, destination::m_no, destination::m_phyRate, packet::m_size.
Referenced by transmitNextPackets.
double fifoOFDMAOptimal(std::list< packet > &buffer, double currentTime)
Calculate transmission time for FIFO OFDMA Optimal, which sends all packet has different destination in the buffer (cause the paralel, so can not send 2 or more packets to the same destination in the same time) . The combination of sent packet is depend on the Objective Function value of every combination packet in the buffer. FIFO here is the prior process taking the first packet1: Example: [[packet 1], [packet1, packet2], [packet1, packet2, packet3], ...] (each of this packet has different destination) => The packets combination will be bruteforce with each combination of Resource Unit to find the Optimal Resource Unit combination correspond to packet combination. Do the same sequence with every combination => Result the most optimal packet combination (biggest Objective Function). Then calculate time for transfer this combination and delete it from initial buffer.
buffer Current list of packet queueing currentTime destList Store the destination of "new destination" packet tmpList Temporary list for storing "new destination" packet object newDestList List of List of packets: [[packet 1], [packet1, packet2], [packet1, packet2, packet3], ...] <double> Transmission time
References buffer, currentTime, getTransmissionTimeOfdmaFrame, maxClient, newDest, objectiveFunction, ruAllocationOptimal, RuType.
Referenced by transmitNextPackets.
double transmitNextPackets(int discipline, list< packet > &buffer, double currentTime)
References buffer, currentTime, fifo, fifoAggregation, fifoOFDMAOptimal.
Referenced by simulateQueue.